apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec: 
  replicas: 2
  selectors:
    matchLabels:
      app: nginx
      tier: frontend
  template:  #pod template
    metadata:
      labels: 
        app: nginx
        tier: frontend
    spec:
  # list of containers
      containers:
      - name: nginx
        image: nginx
       