apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports: 
    - containerPort: 80
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
