apiVersion: v1
kind: Pod
metadata:
  name: hello-pod

spec: 
  containers:
  - name: noginx
    image: noginx
    ports:
    - containerPort: 80
    resources: 
      requests:
        cpu: "100m"
        memory: "68mi"
      limits:
        cpu: "200m"
        memory: "128mi"